### ISSUE TITLE
firebase-auth-manager misfires error

### ISSUE THREAD

**Issue by brezinajn** [MeTaNoV/firebase-element-extended#1]
firebase-auth-manager fires error even for errors not related with firebase-element-extended. I presume it's due to [this](https://github.com/MeTaNoV/firebase-element-extended/blob/master/firebase-auth-manager.html#L109) line.

**Comment by GeoloeG-IsT** [comment]
Thanks for your feedback, indeed, it happened also to me some times. I will check now if the event have detail to publish to the Error Dialog, else I'll output error to the console. 
BTW, can you reproduce the source of the error?
If you have any other feedback, do not hesitate! (I am quite often on the Slack channel of Polymer of you want to say Hi! :smile:)

**Comment by brezinajn** [comment]
Sorry. I'm unable to reproduce the error anymore :D

**Comment by GeoloeG-IsT** [comment]
I fixed some minor bugs, might have been related! :)
