### ISSUE TITLE
Update to use firebase 3.0 (firebase.google.com)

### ISSUE THREAD

**Issue by mm-gmbd** [MeTaNoV/firebase-element-extended#15]
This is a great set of starter elements - would love to see them updated to the new Firebase!

**Comment by helmuthb** [comment]
Hi @MeTaNoV feel free to have a look at my fork at https://github.com/helmuthb/firebase-element-extended/tree/firebase3 - not ready for a pull request but at least it does what I needed

**Comment by GeoloeG-IsT** [comment]
Hi @helmuthb , thanks and I will take a look, and it should not be that complicated to do, I just need to find the time to do it properly! :)

**Comment by GeoloeG-IsT** [comment]
@helmuthb I did a PR out of your contribution, many thx and will continue with the missing part! Feel free to test when I'll tag a new release!
