### ISSUE TITLE
firebase-auth-manager _user initialization

### ISSUE THREAD

**Issue by mm-gmbd** [MeTaNoV/firebase-element-extended#6]
In _firebase-auth-manager_, the property `_user` is automatically set to an empty object:

```
_user: {
  type: Object,
  value: function() { return {}; }
},
```

Now, the property `_profileLocation` is defined as the following:

```
_profileLocation: {
  type: String,
  computed: '_computeProfileLocation(location,_user)',
  value: ""
},
```

And the function `_computeProfileLocation` is defined as the following:

```
_computeProfileLocation: function(location,user) {
  if (user) {
    return [location, 'profile', user.uid].join('/');
  } else {
    return "";
  }
},
```

Because `_user` is initialized to an empty object, the statement `if (user)` _always_ passes and a query is attempted to the following document location: 

```
https://<FIREBASE>.firebaseio.com/profile
```

Once the user object is updated by `firebase-auth`, another query is attempted to the following location:

```
https://<FIREBASE>.firebaseio.com/profile/<user.uid>
```

I presume this is _not_ the intended behavior, so either the _user variable should be initialized to `null`, or the if statement should be `if(user && user.uid)`.

If this _is_ the intended behavior, I'd be interested to know why :)

**Comment by GeoloeG-IsT** [comment]
let me check that! :)

**Comment by GeoloeG-IsT** [comment]
this was just a bug! Pushing the correction!
